In [2]:
from model_plus import NewNet
from PIL import Image
import torch
from torchvision.transforms import Compose, Grayscale, ToTensor
import matplotlib.pyplot as plt
import cv2
import numpy as np
from sklearn.metrics import f1_score
%matplotlib inline

In [75]:
model = NewNet()
model.load_state_dict(torch.load('./model/NewNet_model_Class6.pt'))
model.eval()
model = model.to('cuda')
imgpath = "./image/Class6/img1.PNG"
img = Image.open(imgpath).convert('L')
transform = Compose([Grayscale(), ToTensor()])
img = transform(img)
img = img.to('cuda')
img = img.unsqueeze(0)
EDX = model(img)
residual = torch.abs(img[0][0]-EDX[0][0])

In [76]:
x = img.detach().cpu().numpy()[0][0]
EDX = EDX[0][0].detach().cpu().numpy()

In [12]:
x_array = np.array(x).flatten()
x_array

array([0.14509805, 0.09019608, 0.15294118, ..., 1.        , 0.9490196 ,
       0.69803923], dtype=float32)

In [13]:
EDX_array = np.array(EDX).flatten()
EDX_array

array([0.14831387, 0.10010412, 0.1558493 , ..., 0.981443  , 0.9397709 ,
       0.6902612 ], dtype=float32)

In [78]:
# F1score
abs_pred = abs(x - EDX)<=0.008
abs_true = np.ones_like(abs_pred)
f1_score(abs_true, abs_pred, average='macro')

0.9900831968337103

In [100]:
# acc
from sklearn.metrics import accuracy_score

abs_pred = abs(x_array - EDX_array)<=0.004
abs_true = np.ones_like(abs_pred)
# 如果normalize为True，返回正确分类的得分（浮点型），否则返回分类正确的样本数量（整型）
accuracy_score(abs_true, abs_pred, normalize=True)

0.8466339111328125

In [67]:
# 精确率
from sklearn.metrics import precision_score

abs_pred = abs(x - EDX)<=0.002
abs_true = np.ones_like(abs_pred)
print(precision_score(abs_true, abs_pred, average='macro'))
# print(precision_score(abs_true, abs_pred, average='micro'))
# print(precision_score(abs_true, abs_pred, average='weighted'))
# print(precision_score(abs_true, abs_pred, average=None))

1.0


In [92]:
abs(x - EDX)<=0.008

array([[ True, False,  True, ...,  True, False,  True],
       [False,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True, False],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [False,  True,  True, ...,  True,  True,  True],
       [ True,  True, False, ..., False, False,  True]])

In [95]:
x_array

array([0.14509805, 0.09019608, 0.15294118, ..., 1.        , 0.9490196 ,
       0.69803923], dtype=float32)

In [96]:
EDX_array

array([0.14831387, 0.10010412, 0.1558493 , ..., 0.981443  , 0.9397709 ,
       0.6902612 ], dtype=float32)